config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }

  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, shallow: true, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: %i[votable commentable] do
      member do
        patch :make_better
        put :make_better
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :other_users, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#index'
  post 'search', to: 'search#searching'

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  =link_to 'Welcome to QnA!', questions_path, class:"btn btn-primary text-light"
  |&nbsp;
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav.font-weight-bolder.text-uppercase.h5.p-2
    - if user_signed_in?
      =current_user.email
      -if current_user.rewards.present?
        =link_to 'Rewards', rewards_path, class:"nav-item nav-link"
      =link_to 'Sign out', destroy_user_session_path, method: :delete,  class:"nav-item nav-link"
    - else
      =link_to 'Sign in', new_user_session_path,  class:"nav-item nav-link"

      =link_to 'Registration', new_user_registration_path,  class:"nav-item nav-link"

  .search-block.float-md-right
    =link_to 'Search' , search_path, class:"btn btn-primary text-light"

app/views/shared/_vote_selector.html.slim
span.col-1.vote-block style ="padding-right: 0px;"
  .row
    -if cannot? :positive_vote, resource
      span.mx-auto =octicon("triangle-up", height: 24, class: 'text-muted', id: 'for-disabled')
    - else
      span.mx-auto = link_to octicon("triangle-up", height: 24, class: 'text-success'),
                                                    polymorphic_path(resource, action: 'positive_vote'),
                                                    method: :patch, remote: true, data: {type: :json},
                                                    id: 'vote-for'
  .row
    span.mx-auto id="vote-score" = resource.rating
  .row
    -if cannot? :negative_vote, resource
      span.mx-auto =octicon("triangle-down", height: 24, class: 'text-muted', id: 'against-disabled')
    -else
      span.mx-auto = link_to octicon("triangle-down", height: 24, class: 'text-danger'),
                                                      polymorphic_path(resource, action: 'negative_vote'),
                                                      method: :patch, remote: true, data: {type: :json},
                                                      id: 'vote-against'