config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }

  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, shallow: true, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: %i[votable commentable] do
      member do
        patch :make_better
        put :make_better
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :other_users, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#index'
  post 'search', to: 'search#searching'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Attachable
  include Votable

  default_scope { order(best: :desc).order(:created_at) }

  has_many :comments, dependent: :destroy, as: :commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, presence: true, length: { minimum: 10 }

  after_create :send_email

  def up_to_best!
    Answer.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def send_email
    AnswersSubscriptionsJob.perform_later(question, self) if question.subscriptions.exists?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  after_action :publish_answer, only: %i[create]

  include Voted

  authorize_resource

  def index
    question.answers
  end

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    authorize! :update, answer
    answer.update(answer_params)
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def make_better
    answer.up_to_best!
  end

  private

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : Answer.new
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def publish_answer
    return if answer.errors.any?

    ActionCable.server.broadcast("answers_for_question_#{question.id}",
                                 author: answer.user.email,
                                 rating: answer.rating,
                                 answer: answer,
                                 links: answer.links)
  end

  helper_method :question
  helper_method :answer

  def answer_params
    params.require(:answer).permit(:body, :author_id,
                                   files: [],
                                   links_attributes: %i[id name url _destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < BaseController
      before_action :set_question, only: %i[index create]
      before_action :set_answer, only: %i[show update destroy]

      authorize_resource

      def index
        render json: @answers, each_serializer: AnswersSerializer
      end

      def show
        render json: @answer
      end

      def new; end

      def create
        @answer = @question.answers.new(answer_params)
        @answer.user = current_resource_owner
        if @question.save
          head 200
        else
          head 422
        end
      end

      def update
        if @answer.update(answer_params)
          head 200
        else
          head 422
        end
      end

      def destroy
        @answer.destroy
      end

      private

      def set_question
        @question = Question.find(params[:question_id])
        @answers = @question.answers
      end

      def set_answer
        @answer = Answer.find(params[:id])
      end

      def answer_params
        params.require(:answer).permit(:body, :author_id)
      end
    end
  end
end

app/views/answers/_answer.html.slim
-cache answer do
  .row.p-2
    .col-12
      .row class='answer_id_#{answer.id}'
        =render 'shared/vote_selector', resource: answer
        span.col-11.my-auto style ="padding-left: 0px;"
          span.best-block
            - if can? :make_better, answer
              - if answer.best?
                = link_to 'Best', make_better_answer_path(answer), method: :put, class: 'btn-sm btn-success text-light mt-3 mr-2', remote: true, id: 'answer-best'
              -else
                = link_to 'Best', make_better_answer_path(answer), method: :put, class: 'btn-sm btn-light text-muted mt-3 mr-2', remote: true, id: 'answer-best'
            -else
              - if answer.best?
                = content_tag(:span, 'Best', class: 'btn-sm btn-success text-light mt-3 mr-2', remote: true, id: 'answer-usual', :disabled => true)
              -else
                = content_tag(:span, 'usual', class: 'btn-sm btn-light text-muted mt-3 mr-2 .disable', id: 'answer-usual', :disabled => true)
          span.list-answer
            =render 'answers/answer_list', answer: answer

app/views/answers/_answer_list.html.slim
span class='answer_id_#{answer.id}_body'
 -cache answer do
    = answer.body
    - if can? :update, answer
      span style='font-size: 8pt'
        |&nbsp;
        = link_to 'Edit', '', class: 'btn-sm btn-outline-info mt-3 answer-edit', data: { answer_id: answer.id }
      span style='font-size: 8pt'
        |&nbsp;
        =link_to 'Delete', answer_path(answer), method: :delete, data: {confirm: 'Are you sure?'}, id: 'answer_delete', remote: true, class: ' btn-sm btn-outline-danger mt-3'
    span style='font-size: 9pt'
      br
      |&nbsp; answer's author:
            #{answer.user.email}
    - if answer.files.attached?
      br
      =render 'attachments/attachment', resource: answer
    - if answer.links.exists?
      span style='font-size: 9pt'
        br
        |links:
        = render 'links/link_list', resource: answer
    .answer-comment-errors.text-danger style='font-size: 10pt'
      = render 'shared/errors', resource: @comment
    span
      fieldset.answer-comments
        legend.w-auto.text-primary style='font-size: 8pt' comments:
        - if answer.comments.exists?
          = render answer.comments
        - else
          span.text-secondary.empty style='font-size: 10pt' 0 comment's
        = render 'comments/comment_form', resource: Comment.new, path: answer_comments_path(answer)
      - if signed_in?
        = content_tag(:span, class: 'text-primary comment-button', style: 'font-size: 8pt')
          = octicon('comment', height: 16, class: 'mb-1')
          = link_to ' add comment', '', id: 'answer-comment', style: 'text-decoration: none;', remote: true, data: { answer_id: answer.id }
    - if can? :update, answer
    span class ="edit-answer-#{answer.id} hidden"
      = simple_form_for answer, class: 'hidden ml-1',  remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.text_area :body, style: 'width: 60%'
        span.attached-links-form
          = f.simple_fields_for :links do |links|
            = render 'links/fields', f: links
            .links
            = link_to_add_association octicon('plus-small', height: 32, class: 'text-success'), f, :links, partial: 'links/fields'
        - if answer.files.attached?
          br
          span style='font-size: 9pt'
            |files:
            =render 'attachments/attachment_edit', resource: answer
          br
        = f.file_field :files, multiple: true,  direct_upload: true, style: 'width: 30%', class: 'btn-sm form-control-file mr-3 mb-2'
        = f.submit 'Save', class: 'btn btn-outline-info btn-sm'
br

app/views/answers/_form.html.slim
= simple_form_for @answer, url: question_answers_path(question), remote: true do |f|
  = f.input :body, label: 'Your answer:', input_html: { class: "col-md-8"}
  -if !signed_in?
    =link_to 'Add a answer','', class: 'd-inline btn btn-primary disabled', :disabled => true
    span.text-secondary.ml-5.d-inline You need to sign in or sign up before continuing.
  -else
    = f.file_field :files, multiple: true, direct_upload: true, class: 'btn-sm form-control-file mr-3 mb-2', style: 'width: 60%'
    = f.simple_fields_for :links do |links|
      = render 'links/fields', f: links
    .links
      = link_to_add_association octicon('plus-small', height: 32, class: 'text-success'), f, :links, partial: 'links/fields'
      br
    =f.submit 'Add a answer', class: 'btn btn-outline-primary'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('#new_answer #answer_body').val('');
  location.reload();
<% end %>

app/views/answers/destroy.js.erb
 $('.answer_id_<%= answer.id %>').remove();

app/views/answers/make_better.js.erb
$('.answers').html("<%= j render  answer.question.answers %>");

app/views/answers/new.html.slim
= render 'shared/errors', resource: @answer

= form_with model: @answers, local: true do |f|
  =f.label :body
  =f.text_area :body

  =f.submit 'Add a answer'

app/views/answers/update.js.erb
$('.answer-edit-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if answer.errors.blank? %>
    $('.answer_id_<%= answer.id %> .list-answer').html('<%= j render 'answers/answer_list', answer: answer %>');
    $('#edit-answer-<%= answer.id %>').hide()
    $('[data-answer-id="<%= answer.id %>"]').show()
    location.reload();
<% end %>