config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }

  concern :votable do
    member do
      patch :positive_vote
      patch :negative_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, shallow: true, concerns: %i[votable commentable] do
    resources :answers, shallow: true, only: %i[create destroy update], concerns: %i[votable commentable] do
      member do
        patch :make_better
        put :make_better
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :other_users, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  get 'search', to: 'search#index'
  post 'search', to: 'search#searching'

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: %i[create index show]
  before_action :set_subscription, only: :destroy

  authorize_resource

  def create
    @question.subscriptions.create(user_id: current_user.id)
  end

  def destroy
    @question = @subscription.question
    @subscription.destroy
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_subscription.html.slim
.subscriptions
  -if current_user.nil?
    = content_tag(:span, octicon("bookmark", height: 48, class: 'text-muted float-right', id: 'mark-disabled'), '')
  -else
    -if question.subscribed?(current_user)
      = link_to(octicon("bookmark", height: 48, class: 'text-warning float-right', id: 'mark-enabled'), subscription_path(question.subscription(current_user)), method: :delete, data: {confirm: 'Are you sure?'}, remote: true)
    -else
      = link_to(octicon("bookmark", height: 48, class: 'text-muted float-right', id: 'mark-disabled'), question_subscriptions_path(question), method: :post, remote: true)

app/views/subscriptions/create.js.erb
$('.subscriptions').html('<%= j render 'subscriptions/subscription', question: @question %>');

app/views/subscriptions/destroy.js.erb
$('.subscriptions').html('<%= j render 'subscriptions/subscription', question: @question %>');